config/routes.rb
Rails.application.routes.draw do
  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v2/payments' => 'payments#new', as: :new_checkout
  post '/v2/payments' => 'payments#create', as: :new_charge

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v2/cameras'), as: :root
  get '/v2/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras' => 'cameras#index'  # temporary route
  get '/v2/cameras/new' => 'cameras#new', as: :cameras_new
  post '/v2/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v2/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id' => 'cameras#single' # temporary route
  get '/v2/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v2/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v2/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v2/cameras/:id/archives/:archive_id/play' => 'pages#play', as: :play_clip
  get '/v2/cameras/:id/share/request' => 'pages#revoke_request'
  get '/v2/swagger' => "pages#swagger"
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v2/cameras/:id/*subpath' => 'cameras#single'

  get '/v2/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v2/archives' => 'archives#index', as: :archives_index
  get '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/add' => redirect('/v2/cameras/new')
  get '/v2/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v2/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v2/users/signup' => 'users#new', as: :signup
  get '/v1/users/signup' => 'users#new' # temporary route
  post '/v2/users/signup' => 'users#create'
  post '/v1/users/signup' => 'users#create' # temporary route
  get '/v2/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v2/users/password-reset' => 'users#password_reset_request'
  get '/v2/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v2/users/password-new' => 'users#password_update'
  get '/confirm' => 'users#confirm'
  get '/v2/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  get '/v2/users/signout' => 'sessions#destroy'
  get '/v1/users/signout' => 'sessions#destroy' # temporary route
  delete '/v2/users/signout' => 'sessions#destroy', as: :signout

  # Removed username from url
  get '/v2/users/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/v2/users/account' => 'users#settings', as: :user_settings
  get '/v2/users/settings', to: redirect("/v2/users/account")
  delete '/v2/users/account' => 'users#delete'
  post '/v2/users/account' => 'users#settings_update'
  put '/v2/users/password/change' => 'users#change_password', as: :user_change_password
  # Removed username from url

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'

  get '/test' => 'cameras#test', as: :test
  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

app/models/evercam_models/user.rb
require 'bcrypt'
class User < Sequel::Model
  include BCrypt
  many_to_one :country
  one_to_many :cameras, key: :owner_id
  one_to_many :grants,
              class: 'AccessToken',
              conditions: Sequel.negate(client_id: nil),
              key: :user_id
  one_to_one  :token,
              class: 'AccessToken',
              conditions: { client_id: nil },
              after_load: proc { |u| u.send(:ensure_token_exists) },
              key: :user_id
  one_to_many :camera_shares

  def self.by_login(login)
    username_query = Sequel.ilike(:username, login)
    email_query = Sequel.ilike(:email, login)
    where(username_query).or(email_query).first
  end

  def fullname
    [firstname, lastname].join(' ')
  end

  def password
    Password.new(values[:password])
  end

  def password=(val)
    values[:password] = Password.create(val, cost: 10)
  end

  def before_save
    values[:encrypted_password] = values[:password]
    super
  end

  def confirmed?
    false == confirmed_at.nil?
  end

  def allow?(token)
    if token
      if token.user == self
        return true
      end
    end
  end

  def validate
    super
    errors.add(:firstname, "is invalid") if (/^[\p{Word}\s,.']+$/ =~ firstname).nil?
    errors.add(:lastname, "is invalid") if (/^[\p{Word}\s,.']+$/ =~ lastname).nil?
    errors.add(:email, "is invalid") if (/^.+@.+\..+$/ =~ email).nil?
  end

  private

  def ensure_token_exists
    self.token ||= AccessToken.new(
      expires_at: Time.at(2**31))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:new, :create, :confirm,
                     :password_reset_request, :password_update, :password_update_form]
  layout "bare-bones", except: [:settings, :delete]
  include SessionsHelper
  include ApplicationHelper
  require "date"

  def new
    if params[:key] && current_user
      sign_out
    end
    unless current_user.nil?
      single_camera_redirection(cameras_index_path)
    end
    @share_request = nil
    get_referral_url()

    if params[:key]
      @share_request = CameraShareRequest.where(
        key: params[:key]
      ).first
      session[:referral_url] = "#{@share_request.user.email} shared #{@share_request.camera.name}"
      unless @share_request.nil?
        user = User.where(Sequel.ilike(:email, @share_request.email)).first
        unless user.blank?
          flash[:error] = "This signup link has already been used by #{@share_request.email.downcase}, You should either login to your existing account or create a new account."
          redirect_to signin_path
        end
      end
    end
  end

  def create
    user = params[:user]
    begin
      if user.nil?
        raise "No user details specified in request."
      end
      if request.safe_location && Evercam::Config.env == :production
        params[:country] = request.safe_location.country_code.downcase
      end

      get_evercam_api.create_user(
        user['firstname'],
        user['lastname'],
        "",
        user['email'],
        user['password'],
        ENV['WEB_APP_TOKEN'],
        params[:country],
        params[:key],
        session[:referral_url]
      )

      user = User.where(Sequel.ilike(:email, user[:email])).first
      sign_in user
      session[:referral_url] = nil
      update_user_intercom user
      single_camera_redirection(cameras_index_path)
    rescue => error
      if error.kind_of?(Evercam::EvercamError)
        if error.message.eql?("Invalid token.")
          flash[:message] = error.message
        else
          response = instance_eval{(error.message).first}
          if error.try(:status_code).present? && error.status_code.equal?(400)
            assess_field_errors(response)
          else
            flash[:message] = response.last.first
          end
        end
      else
        flash[:message] = "An error occurred creating your account. Please check "\
                            "the details and try again. If the problem persists, "\
                            "contact support."
      end
      Rails.logger.error "Exception caught in create user request.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      render action: "new", user: user
    end
  end

  def confirm
    user = User.by_login(params[:u])
    unless user.nil?
      code = Digest::SHA1.hexdigest(user.username + user.created_at.utc.to_s)
      if params[:c] == code
        user.confirmed_at = Time.now
        user.save
        flash[:notice] = 'Successfully activated your account'
      else
        flash[:notice] = 'Activation code is incorrect'
      end
    end
    redirect_to signin_path
  end

  def settings
    @cameras = load_user_cameras(true, false)
    @countries = Country.all
    @countries.sort_by! { |e| e.name.downcase }
    render layout: "user-account"
  end

  def delete
    begin
      get_evercam_api.delete_user(current_user.email)
      redirect_to good_bye_path
    rescue => error
      Rails.logger.error "Exception caught deleting user.\nCause: #{error}\n" +
                           error.backtrace.join("\n")
      flash[:message] = "An error occurred deleting user. Please try again "\
                      "and, if the problem persists, contact support."
      redirect_to user_settings_path
    end
  end

  def settings_update
    begin
      user_email = current_user.email
      parameters = {}
      parameters[:firstname] = params['user-firstname'] if params.include?('user-firstname')
      parameters[:lastname] = params['user-lastname'] if params.include?('user-lastname')
      parameters[:telegram_username] = params['telegram-username'] if params.include?('telegram-username')
      parameters[:country] = params['country'] if params.include?('country')
      if params.include?('email')
        unless params['email'] == current_user.email
          parameters[:email] = params['email']
          parameters[:username] = params['email']
          user_email = params['email']
        end
      end
      if !parameters.empty?
        old_email = current_user.email
        get_evercam_api.update_user(current_user.username, parameters)
        session[:user] = User.by_login(user_email).email
        update_user_intercom(current_user, old_email)
        refresh_user
      end

      if old_email != current_user.email && send_confirmation_email
        flash[:message] = 'Settings updated successfully and we’ve sent you a confirmation email with instructions.'
      else
        flash[:message] = 'Settings updated successfully'
      end
    rescue => error
      Rails.logger.error "Exception caught in update user request.\nCause: #{error}\n" +
          error.backtrace.join("\n")
      if error.kind_of?(Evercam::EvercamError)
        response = instance_eval{(error.message).first}
        if response[1] && response[1][0]
          flash[:message] = response[1][0]
        else
          flash[:message] = "An error occurred updating your details. Please try "\
          "again and, if the problem persists, contact support."
        end
      else
        flash[:message] = "An error occurred updating your details. Please try "\
                        "again and, if the problem persists, contact support."
      end
    end
    redirect_to user_settings_path
  end

  def change_password
    begin
      user = User.by_login(current_user.email)
    rescue NoMethodError => error
      Rails.logger.error "Error caught fetching user details.\nCause: #{error}\n" + error.backtrace.join("\n")
    end

    if !user.nil? and user.password == params['current-password']
      user.update(password: params['new-password'])
      user.save
      flash[:message] = 'Password updated successfully'
    else
      flash[:message] = 'Invalid Current Password'
    end
    redirect_to user_settings_path
  end

  def password_reset_request
    get_referral_url()
    email = params[:email].downcase if params[:email]
    unless email.nil?
      user = User.by_login(email)

      if user
        t = Time.now
        if user.reset_token.present? and user.token_expires_at.present? and user.token_expires_at > t
          expires = user.token_expires_at
          token = user.reset_token
        else
          expires = t + 24.hour
          token = SecureRandom.hex(16)
        end

        user.update(reset_token: token, token_expires_at: expires)

        UserMailer.password_reset(email, user, token).deliver_now
        flash.now[:message] = "We’ve sent you an email with instructions for changing your password."
      else
        flash.now[:message] = "Email address not found."
      end
    end
  end

  def password_update_form
    username = params[:u]
    user = User.by_login(username)
    if user.nil? or user.token_expires_at.blank? or user.token_expires_at < Time.now
      @expired = true
    else
      @expired = false
    end
    render "password_update"
  end

  def password_update
    token = params[:token]
    username = params[:username]
    user = User.by_login(username)
    if user.nil? or token != user.reset_token or user.token_expires_at < Time.now
      flash[:message] = 'Invalid username or token'
    else
      user.update(reset_token: '', token_expires_at: Time.now)
      user.password = params[:password]
      user.save
      sign_in user
      redirect_to cameras_index_path, message: 'Your password has been changed'
    end
  end

  def resend_confirmation_email
    result = send_confirmation_email
    unless result
      flash[:message] = 'We’ve sent you a confirmation email with instructions.'
    else
      flash[:message] = t("errors.user_not_found_error")
    end
    redirect_to user_settings_path
  end

  private

  def send_confirmation_email
    user = User.where(Sequel.ilike(:email, current_user.email)).first
    unless user.nil?
      code = Digest::SHA1.hexdigest(user.username + user.created_at.utc.to_s)
      UserMailer.resend_confirmation_email(user, code).deliver_now
      true
    else
      false
    end
  end

  def assess_field_errors(error)
    field_errors = {}
    field_errors[error.first] = error.last.first
    flash[:field_errors] = field_errors
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_background_video.html.erb
<div id="evercam-video-section" class="evercam-video-section">
  <video autoplay loop muted poster="/assets/poster.jpg" id="loop-video">
  <source src="https://evercam.io/gpoview.webm" type="video/webm">
  <source src="https://evercam.io/gpoview.mp4" type="video/mp4">
  <source src="https://evercam.io/gpoview.ogv" type="video/ogg">
</video>
</div>

app/views/users/_section_header.html.erb
<div class="row">
  <div class="section-header">
    <div class="camera-title">
        <%= section_header_title %>
    </div>
  </div>
</div>

app/views/users/applications.html.erb
<!--remove opacity when built-->
<div style="opacity: 0.2;" id="user-applications">
  <div class="row">
    <div class="application col-md-12">
      <h4 class="margin-bottom-15">Snapmail</h4>
      <p>Scheduled Email from your Camera</p>
      <p>Approved: Jan 29 at 8:49 AM</p>
      <div class="btn btn-edit margin-top-10">Revoke</div>
    </div>
    <div class="application col-md-12">
      <h4 class="margin-bottom-15">AsTimeGoes.by</h4>
      <p>Create and share timelapses from your Evercam connected cameras.</p>
      <p>Approved: Jan 14 at 14:39 AM</p>
      <div class="btn btn-edit margin-top-10">Revoke</div>
    </div>
  </div>
</div>

<div class="col-md-12" style="opacity: 0.45" >
  <p>Coming Soon...</p>
</div>

app/views/users/new.html.erb
<% provide(:title, "Create New Account") %>
<section id="new-account" class="site-min-height">
  <%= render partial: "users/background_video" %>
  <div class="container section section-position no-padding" id="new-account">
    <div id="signin" class="col-md-12 text-center no-padding">
      <div class="bb-alert alert alert-danger" style="display:none;">
        <span></span>
      </div>
      <div id="registration" class="center-div width-400 col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="branding logo-padding">
          <%= link_to root_path, class: 'sign-in-logo' do %>
            <%= image_tag("evercam_logo.png", :class => "svg-logo", alt: "Evercam.io") %>
          <% end %>
        </div>
        <div class="col-sm-12 padding-left-right-40">
          <%= form_for(:user, url: signup_path, :html => { :id => "create-account" } ) do |f| %>
            <% field_errors = (flash[:field_errors] || {}) %>

            <div class="text-center">
              <div class="col-sm-12 no-padding margin-top-bottom-15 form-group<%= field_errors.include?("firstname") ? " has-error" : "" %>">
                <%= f.text_field :firstname, value: params.fetch('user', {})[:firstname], class: "form-control", "required" => "" %>
                <% if field_errors.include?("firstname") %>
                  <span class="help-block arrow_box form-error text-left"><%= field_errors["firstname"] %></span>
                <% end %>
                <%= f.label :firstname, 'First Name', class: "float-label" %>
                <span id="invalid-userfirst-name" class="username-error float-left">Last names can consist of alphabetical characters and spaces only.</span>
              </div>
            </div>

            <div class="text-center">
              <div class="col-sm-12 no-padding margin-top-bottom-15 form-group<%= field_errors.include?("lastname") ? " has-error" : "" %>">
                <%= f.text_field :lastname, value: params.fetch('user', {})[:lastname], class: "form-control", "required" => "" %>
                <% if field_errors.include?("lastname") %>
                  <span class="help-block arrow_box form-error text-left"><%= field_errors["lastname"] %></span>
                <% end %>
                <%= f.label :lastname, 'Last Name', class: "float-label" %>
                <span id="invalid-userlast-name" class="username-error float-left">Last names can consist of alphabetical characters and spaces only.</span>
              </div>
            </div>

            <div class="text-center">
              <div id="signup-email" class="col-sm-12 no-padding margin-top-bottom-15 form-group<%= field_errors.include?("email") ? " has-error" : "" %>">
                <% if @share_request.nil? %>
                  <%= f.text_field :email, value: params.fetch('user', {})[:email], class: "form-control", "required" => "" %>
                  <%= f.label :email, 'Email', class: "float-label" %>
                <% else %>
                  <%= f.text_field :email, value: @share_request.email, readonly: 'readonly', class: "form-control grey-background" %>
                <% end %>
                <% if field_errors.include?("email") %>
                  <span class="help-block arrow_box form-error text-left"><%= field_errors["email"] %></span>
                  <%= f.label :email, 'Email', class: "float-label" %>
                <% end %>
                <img src="/assets/refresh.gif" class="refresh-gif icon-position email-loading-icon">
                <span id="email-error-block" class="username-error">Email has already been taken.</span>
                <span id="incorrect-email-block" class="username-error">You have not type correct Email address.</span>
                <span id="email-not-available" class="red hide"><i class="fa fa-times icon-position icon-font"></i></span>
                <span id="email-available" class="green hide"><i class="fa fa-check icon-position icon-font"></i></span>
              </div>
            </div>

            <div class="text-center">
              <div class="col-sm-12 no-padding margin-top-bottom-15 form-group<%= field_errors.include?("password") ? " has-error" : "" %>">
                <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
                <% if field_errors.include?("password") %>
                  <span class="help-block form-error arrow_box text-left"><%= field_errors["password"] %></span>
                <% end %>
                <%= f.label :password, class: "float-label" %>
                <span id="invalid-password" class="username-error">Password should be at least 6 characters.</span>
              </div>
            </div>
            <div class="col-sm-12 no-padding text-center">
              <%= f.submit "Create Account", class: "btn btn-large btn-primary width100" %>
            </div>

            <% if @share_request %>
              <input type="hidden" name="key" id="key" value="<%= @share_request.key %>"/>
            <% end %>
          <% end %>
          <div class="col-md-12 col-sm-12 text-center grey margin-top-20">
            <p>Already have an account? <%= link_to "Sign in", signin_path %></p>
          </div>
          <div class="col-md-12 col-sm-12 text-center grey">
            <a href="https://www.evercam.io/terms" target="blank">Terms of Use</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
  if (!window.Evercam) {
    window.Evercam = {};
  }


  Notification.init(".bb-alert");
  <% if flash[:message] %>
  Notification.show('<%= flash[:message] %>');
  <% end %>

  window.Evercam.ENV = '<%= Rails.env %>';
  $(function () {
    $("alert").on("click", function () {
      $("." + $(this).attr("data-hide")).hide();
      });
  });
  $.validate();

  $( document ).ready(function() {
    if ($('div').find("input[type=text]").val() == '') {
      $('.form-error').hide();
    }
    // $("#referral_url").val(document.referrer);
  });
  $('#create-account').submit(function(){
    $(this).find('input:text').each(function(){
      $(this).val($.trim($(this).val()));
    });
  });
</script>

<script>
  $(document).ready(function () {
    window.initializeVideoBackground();
  });
</script>

app/views/users/password_reset_request.html.erb
<% provide(:title, "Evercam: Password Reset") %>
<%= render partial: "users/background_video" %>
<div class="container section-position" id="pass-reset">
  <div class="bb-alert alert alert-info" style="display:none;">
    <span></span>
  </div>
  <div class="row">
    <div class="center-div width-400 col-md-4 panel col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class="col-md-12 text-center">
        <div class="branding logo-padding">
          <%= link_to image_tag("evercam_logo.png", class: "svg-logo", alt: "Evercam.io"), root_path %>
        </div>
      </div>
      <div class="col-md-12 col-xs-12 reset-password padding-left-right-40">
        <form role="form" method="post" class="center-block">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

          <div class="form-group">
            <div class="input-icon right">
              <i class="icon">@</i>
              <input type="email" value="" class="form-control reset-password-email" id="email" name="email" placeholder="Enter your email address">
            </div>
          </div>
          <input type="submit" class="btn btn-primary width-full" value="Reset">
        </form>
      </div>
      <div class="clear-f"></div>
    </div>
  </div>
</div>

<script>
  Notification.init(".bb-alert");
  <% if flash[:message] %>
  Notification.show('<%= flash[:message] %>');
  <% end %>
</script>

<script>
  $(document).ready(function () {
    window.initializeVideoBackground();
  });
</script>

app/views/users/password_update.html.erb
<% provide(:title, "Evercam: Password Update") %>
<%= render partial: "users/background_video" %>
<div class="bb-alert alert alert-info" style="display:none;">
  <span></span>
</div>
<div class="container section-position" id="pass-reset">
  <div class="row">
      <div class="center-div width-400 col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-xs-offset-1 panel">
        <div class="col-md-12 text-center">
          <div class="branding logo-padding">
            <%= link_to image_tag("evercam_logo.png", class: "svg-logo", alt: "Evercam.io"), root_path %>
          </div>
        </div>
        <% if @expired %>
        <div class="col-md-12 text-center">
          <div class="col-md-12" id="user-settings"><h4>Link Expired</h4></div>
          <div class="col-md-12 col-xs-12 reset-password">
            <p>It looks like this password reset link has expired and can no longer be used.</p>
            <p><%= link_to "Get a new password link", password_reset_path %></p>
          </div>
        </div>
        <% else %>

        <div class="col-md-12 col-xs-12 reset-password padding-bottom-10">
          <form role="form" method="post" class="center-block">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

            <div class="form-group">
              <div class="input-icon right">
                <i class="icon-lock"></i>
                <input type="password" value="" class="form-control" id="password" name="password" placeholder="Enter New Password" required>
              </div>
            </div>
            <input type="hidden" name="username" value="<%= params[:u] %>">
            <input type="hidden" name="token" value="<%= params[:t] %>">
            <input type="submit" class="btn btn-primary width-full" value="Enter">
          </form>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
  Notification.init(".bb-alert");
  <% if flash[:message] %>
  Notification.show('<%= flash[:message] %>');
  <% end %>
</script>

<script>
  $(document).ready(function () {
    window.initializeVideoBackground();
  });
</script>

app/views/users/settings.html.erb
<% provide(:title, "Evercam: User Settings") %>
<div id="user-settings">
  <div class="page-content-wrapper settings-tab" id="manage-account">
    <div class="page-content">
      <div class="tabbable tabbable-custom">
        <div class="center-tabs">
          <ul id="ul-nav-tab" class="nav nav-tabs">
            <li class="active">
              <a data-toggle="tab" data-target="#account" class="nav-tab-account nav-tab-">Account</a>
            </li>
            <li>
              <a data-toggle="tab" data-target="#password" class="nav-tab-details">Password</a>
            </li>
            <li>
              <a data-toggle="tab" data-target="#activities" class="nav-tab-activities">Activities</a>
            </li>
            <li>
              <a data-toggle="tab" data-target="#embedded-live-view" class="nav-tab-live nav-tab-">Live View Widget</a>
            </li>
            <li>
              <a data-toggle="tab" data-target="#embedded-recordings" class="nav-tab-recording-widget">Recording Widget</a>
            </li>
            <li>
              <a data-toggle="tab" data-target="#api-call" class="nav-tab-api">API</a>
            </li>
          </ul>
        </div>
        <div class="tab-content">
          <div id="account" class="account-setting margin-top-20 tab-pane active">
            <%= render partial: "users/settings/account_tab" %>
          </div>
          <div id="password" class="account-password margin-top-20 tab-pane">
            <%= render partial: "users/settings/password_tab" %>
          </div>
          <div id="activities" class="user-history tab-pane">
            <%= render partial: "users/settings/user_activities_tab" %>
          </div>
          <div id="embedded-live-view" class="tab-pane margin-top-20">
            <%= render partial: "widgets/widgets_new" %>
          </div>
          <div id="embedded-recordings" class="tab-pane margin-top-20">
            <%= render partial: "widgets/widget_snapshot_navigator" %>
          </div>
          <div id="api-call" class="tab-pane margin-top-20">
            <%= render partial: "users/settings/simple_api_calls" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
    window.initializeUserAccount();
    window.initializeUserActivity();
    <% if flash[:message] %>
    Notification.show('<%= flash[:message] %>');
    <% end %>
  });
</script>