config/routes.rb
Rails.application.routes.draw do
  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v2/payments' => 'payments#new', as: :new_checkout
  post '/v2/payments' => 'payments#create', as: :new_charge

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v2/cameras'), as: :root
  get '/v2/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras' => 'cameras#index'  # temporary route
  get '/v2/cameras/new' => 'cameras#new', as: :cameras_new
  post '/v2/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v2/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id' => 'cameras#single' # temporary route
  get '/v2/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v2/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v2/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v2/cameras/:id/archives/:archive_id/play' => 'pages#play', as: :play_clip
  get '/v2/cameras/:id/share/request' => 'pages#revoke_request'
  get '/v2/swagger' => "pages#swagger"
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v2/cameras/:id/*subpath' => 'cameras#single'

  get '/v2/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v2/archives' => 'archives#index', as: :archives_index
  get '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v2/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/add' => redirect('/v2/cameras/new')
  get '/v2/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v2/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v2/users/signup' => 'users#new', as: :signup
  get '/v1/users/signup' => 'users#new' # temporary route
  post '/v2/users/signup' => 'users#create'
  post '/v1/users/signup' => 'users#create' # temporary route
  get '/v2/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v2/users/password-reset' => 'users#password_reset_request'
  get '/v2/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v2/users/password-new' => 'users#password_update'
  get '/confirm' => 'users#confirm'
  get '/v2/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  get '/v2/users/signout' => 'sessions#destroy'
  get '/v1/users/signout' => 'sessions#destroy' # temporary route
  delete '/v2/users/signout' => 'sessions#destroy', as: :signout

  # Removed username from url
  get '/v2/users/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/v2/users/account' => 'users#settings', as: :user_settings
  get '/v2/users/settings', to: redirect("/v2/users/account")
  delete '/v2/users/account' => 'users#delete'
  post '/v2/users/account' => 'users#settings_update'
  put '/v2/users/password/change' => 'users#change_password', as: :user_change_password
  # Removed username from url

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'

  get '/test' => 'cameras#test', as: :test
  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

app/views/shared/_dev_sidebar.html.erb
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">

    <ul class="page-sidebar-menu">
      <li>
        <%= link_to cameras_index_path do %>
          <i class="fa fa-camera"></i> Cameras
        <% end %>
      </li>
      <li>
        <a href="/dev"><i class="fa fa-book"></i> Developer</a>
      </li>

      <li class="widgets-menu">
        <a href="<%= widget_live_view_path %>"><i class="fa fa-code"></i> Live View</a>
      </li>

      <li class="widgets-menu">
        <a href="<%= widget_snapshot_navigator_path %>"><i class="fa fa-code"></i> Snapshot Navigator</a>
      </li>

    </ul>
  </div>
</div>

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#dc4c3f">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_header.html.erb
<% if @archive_view %>
  <div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner">
      <div class="menu-toggler sidebar-toggler"></div>
      <a href="javascript:;" class="pull-left menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"></a>
    </div>
  </div>
<% else %>
<div class="page-header <%= "camera-#{@camera['id']}" if @camera %> navbar navbar-fixed-top">
  <div class="page-header-inner">
    <div class="menu-toggler sidebar-toggler"></div>
    <a href="javascript:;" class="pull-left menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"></a>
    <% if params[:controller] == 'cameras' and params[:action] == 'single' %>
      <div class="camera-switch <% if @camera['status'] == "offline" %>camera-offline<% end %>">
        <a class="dropdown-toggle" data-toggle="dropdown">
          <span class="status-circle"></span>
          <span class="camera-name"><%= @camera['name'] %></span>
          <span class="camera-caret"><i class="fa fa-caret-down"></i></span>
        </a>
        <ul class="dropdown-menu scroll-menu" role="menu">
          <% if @cameras %>
            <% @cameras.each do |camera| %>
              <li class="sub-menu-item camera-<%= camera['id'] %> <%= is_active?("/cameras/#{camera['id']}") %> <% if camera['status'] == "offline" %>sidebar-offline<% end %>">
                <%= link_to camera['name'] , cameras_single_path(camera['id'])%>
                <i class="red header-sidebar fa fa-unlink"></i>
              </li>
            <% end %>
          <% else %>
          <li class="sub-menu-item camera-<%= @camera['id'] %> <%= is_active?("/cameras/#{@camera['id']}") %> <% if @camera['status'] == "offline" %>sidebar-offline<% end %>">
            <%= link_to @camera['name'] , cameras_single_path(@camera['id'])%>
            <i class="red header-sidebar fa fa-unlink"></i>
          </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>
<% end %>
<script>
$(document).ready(function () {
  window.initializeHeader();
});
</script>

app/views/shared/_intercom_msg.erb
<% if Evercam::Config.env == :production && @current_user && session[:admin_login].nil? %>
<script id="IntercomSettingsScriptTag">window.intercomSettings = {"email":"<%= @current_user.email %>","user_hash":"<%= OpenSSL::HMAC.hexdigest("sha256", ENV['INTERCOM_API_SECRET'], (@current_user.username || @current_user.email).to_s) %>","user_id":"<%= @current_user.username %>","name":"<%= @current_user.fullname %>","app_id":"<%= ENV['INTERCOM_APP_ID'] %>","widget":{"activator":"#Intercom"},"hide_default_launcher":true};Intercom_script=true;(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/<%= ENV['INTERCOM_APP_ID'] %>';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}};})()</script>
<% else %>
    <script>Intercom_script = false</script>
<% end %>

app/views/shared/_no_script_warning.html.erb
<noscript>
  <div class="noscript-warning">Kindly enable javascript in order to use Evercam properly.</div>
</noscript>

app/views/shared/_ogp_metadata.html.erb
<% if @camera['is_public'] %>
  <meta property='og:title' content='<%= yield(:title) %>'/>
  <meta property='og:image' content='<%= "https://media.evercam.io/v2/cameras/#{@camera['id']}/thumbnail" %>'/>
  <meta property='og:description' content='<%= "#{@camera['name']} is a public camera, Enjoy a live view of this public camera from anywhere. Use your mobile, laptop or tablet from the office, on the road or even on-site." %>'/>
  <meta property='og:url' content='<%= "https://dash.evercam.io/v2/cameras/#{@camera['id']}" %>' />
  <meta property='og:type' content='video.movie' />
<% end %>

app/views/shared/_ogp_metadata_archives.html.erb
<% if @archive
  title = "Evercam: Archive View {#{@archive['title']}}"
  description = "This is a public archive, Enjoy this public video from anywhere. Use your mobile, laptop or tablet from the office, on the road or even on-site."
  release_date = Time.iso8601(@archive['created_at']).utc.strftime("%d/%m/%Y, %H:%M:%S")
  site_name = "Evercam"

  if @archive['type'].eql?("compare")
    title = "Evercam Compare {#{@archive['title']}}"
    from_date = Time.iso8601(@archive['from_date']).utc.strftime("%d/%m/%Y, %H:%M:%S")
    to_date = Time.iso8601(@archive['to_date']).utc.strftime("%d/%m/%Y, %H:%M:%S")
    description = "See progress from #{from_date} to #{to_date} with Evercam Compare"
    site_name = "Evercam Construction Cameras"
  end
%>
<% end %>
<meta property='og:title' content='<%= title %>'/>
<meta property='og:description' content='<%= description %>'/>
<meta property='og:image' content='<%= "https://media.evercam.io/v2/cameras/#{@camera_id}/archives/#{@archive_id}/thumbnail?type=#{@archive_type}" %>'/>
<meta property="og:image:alt" content="<%= @archive['title'] %>" />
<meta property='og:url' content='<%= "https://dash.evercam.io/v2/cameras/#{@camera_id}/archives/#{@archive_id}" %>' />
<meta property='og:site_name' content='<%= site_name %>'/>
<% unless @archive_type.eql?("image") %>
  <meta property='og:type' content='video.other' />
<% end %>

<% if @archive && @archive['type'].eql?("clip") %>
  <%
    from_date = Time.iso8601(@archive['from_date']).utc
    to_date = Time.iso8601(@archive['to_date']).utc
    duration = (to_date - from_date).to_i / 60
  %>
  <meta property='og:video:duration' content='<%= duration %>'/>
  <meta property='og:video:release_date' content='<%= release_date %>'/>
  <meta property='og:video:tag' content='Construction'/>
<% end %>

<meta name="twitter:title" content='<%= title %>' />
<meta name="twitter:description" content='<%= description %>' />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@evrcm" />
<meta name="twitter:image" content='<%= "https://media.evercam.io/v2/cameras/#{@camera_id}/archives/archives/thumbnail?type=#{@archive_type}" %>' />
<meta name="twitter:creator" content="@evrcm" />

app/views/shared/_sidebar.html.erb
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
      <% if @current_user %>
        <li class="cameras-sidebar">
          <div class="sidebar-title">
            <div id="hello" class="col-md-12">
              <%= link_to cameras_index_path do %>
                <img src="/favicon-white-24x24.png" class="camera-icon"><span class="title"> Cameras</span>
              <% end %>
              <span class="camera-fadrop">
                <i class="fa fa-caret-down pull-right title icon-font"></i>
                <i class="fa fa-caret-up title icon-font"></i>
              </span>
            </div>
            <div class="clear-f"></div>
          </div>
        </li>
      <% end %>
      <% unless @archive_view %>
      <li class="cameralist-height title">
        <ul class="sub-menu sidebar-cameras-list">
          <% if @cameras %>
            <% @cameras.each do |camera| %>
              <li class="sub-menu-item camera-<%= camera['id'] %> <%= is_active?("/cameras/#{camera['id']}") %> <% if camera['status'] == "offline" %>sidebar-offline<% end %>" <% if camera['status'] == "offline" %>title="Offline Cause: <%= camera['offline_reason'] %>"<% end %>>
                <% if camera['cloud_recordings'] %>
                  <% recording_status = camera['cloud_recordings'].fetch('status') %>
                  <% recording_duration = camera['cloud_recordings'].fetch('storage_duration') %>
                  <% if recording_duration == -1 %>
                    <% recording_duration = '∞' %>
                  <% end %>
                  <% if recording_status != 'off' && recording_status != 'paused' %>
                    <div id="green-dot-div" class="green-dot-div" title='<%= recording_duration %>'>
                      <i class="fas fa-circle green-dot"></i>
                    </div>
                  <% end %>
                <% end %>
                <%= link_to camera['name'] , cameras_single_path(camera['id']), data: {"camera-id" => camera['id']} %>
                <i class="red header-sidebar fa fa-unlink"></i>
              </li>
            <% end %>
          <% else %>
            <% if @camera %>
            <li class="sub-menu-item public-active-list camera-<%= @camera['id'] %> <%= is_active?("/cameras/#{@camera['id']}") %> <% if @camera['status'] == "offline" %>sidebar-offline<% end %>">
              <span class="title"> <%= @camera['name'] %></span>
              <i class="red header-sidebar fa fa-unlink"></i>
            </li>
            <% else %>
              <li class="sub-menu-item public-active-list">
                <span class="title"> Test Results</span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </li>
      <% end %>
      <% if @current_user %>
        <li class="sidebar-line">
          <%= link_to snapmails_index_path do %>
            <img class="icon-font snapimg" src="//dkzcs7h1dpzak.cloudfront.net/assets/snapmail-fd5f12a06005b85e0247e6fa206e9992c31af9f0c95a79544dcca1f9d216f620.png"><span class="title snapmail-text"> Snapmails</span>
          <% end %>
        </li>
        <li>
          <%= link_to archives_index_path do %>
            <i class="fas fa-archive icon-font"></i><span class="title"> Archives</span>
          <% end %>
        </li>
        <li class="nprogCall">
          <%= link_to map_view_path do %>
            <i class="fa fa-map width-20"></i> Map View
          <% end %>
        </li>
        <li class="nprogCall sidebar-line">
          <%= link_to user_settings_path do %>
            <i class="fa fa-cog icon-font"></i> Settings
          <% end %>
        </li>
        <% if Evercam::Config.env == :production %>
          <li role="presentation">
            <a onclick='$zoho.salesiq.floatwindow.visible("show");'><i class="fa fa-comment icon-font"></i><span class="title"> Live Support</span></a>
          </li>
        <% end %>
        <li class="nprogCall">
          <a rel="nofollow" data-method="delete" href=<%= signout_path %>><i class="fas fa-sign-out-alt right-ajustment icon-font"></i><span class="title"> Sign out </span></a>
        </li>
      <% else %>
        <li class="nprogCall sidebar-line">
          <%= link_to signin_path do %>
            <i class="fas fa-sign-in-alt icon-font"></i> Sign In
          <% end %>
        </li>
        <li class="nprogCall sidebar-line">
          <%= link_to signup_path do %>
            <i class="fa fa-user-plus icon-font"></i> Create New Account
          <% end %>
        </li>
        <li class="nprogCall sidebar-line">
          <%= link_to "https://evercam.io/construction-timelapse/" do %>
            <img src="/favicon-white-24x24.png" class="camera-icon"> About Evercam
          <% end %>
        </li>
        <li class="nprogCall sidebar-line">
          <%= link_to "https://evercam.io/blog" do %>
            <i class="fa fa-rss icon-font"></i> Evercam Blog
          <% end %>
        </li>
      <% end %>

    </ul>
    <input type="hidden" id="controller" value="<%= params[:controller] %>">
  </div>
</div>
<% if @current_user %>
<script type="text/javascript">
  var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode:"758857a8ab7b612c8dad41b0691f8b4f6386f191574508cc8aa8398bb8a1f17f", values:{},ready:function(){}};var d=document;s=d.createElement("script");s.type="text/javascript";s.id="zsiqscript";s.defer=true;s.src="https://salesiq.zoho.com/widget";t=d.getElementsByTagName("script")[0];t.parentNode.insertBefore(s,t);d.write("<div id='zsiqwidget' style='display:none;'></div>");
  $zoho.salesiq.ready=function(embedinfo)
  {
    $zoho.salesiq.visitor.name("<%= current_user.firstname -%>");
    $zoho.salesiq.visitor.email("<%= current_user.username -%>");
  }
</script>
<% end %>

app/views/shared/_stripe.html.erb
<% content_for :javascript do %>
  <script type="text/javascript" src="https://js.stripe.com/v2"></script>
<% end %>

app/views/shared/_user_account_sidebar.html.erb
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu">
      <li>
        <%= link_to cameras_index_path do %>
          <i class="fa fa-camera"></i> Cameras
        <% end %>
      </li>
      <li>
        <%= link_to user_account_path(current_user.username) do %>
          <i class="fa fa-user"></i> Account
        <% end %>
      </li>
      <li>
        <%= link_to password_change_path do %>
          <i class="fa fa-key"></i> Password
        <% end %>
      </li>
      <li>
        <%= link_to user_settings_path do %>
          <i class="fa fa-cog"></i> Settings
        <% end %>
      </li>
      <li>
        <%= link_to apps_path(current_user.username) do %>
          <i class="fa fa-wrench"></i> Applications
        <% end %>
      </li>
    </ul>
  </div>
</div>